#!/usr/bin/env python3

# Kmer creation from Resistance Genes file
ResFile = open("resistance_genes.fsa", "r")

# Read Line by line
    # When ">" , assemble the sequence
info = [] # info line
seq = [] # original sequences
RCseq = [] # Reverse Complement Sequences
data = ''    
for line in ResFile:
        if line.startswith('>'):
            if data:   # have collected a sequence, push to seqs
                seq.append(data)
                data = ''
            info.append(line[:-1])   # Trim '>' from beginning
        else:
            data += line.strip()
    # there will be yet one more to push when we run out
seq.append(data)
    

# Kmer ... with overlap___________________________________
kmers_overlap = []

# Iterate over the sequence data
for item in seq: 
    # Iterate over the nucleotides 
    for letter in range(len(item)-18):
        
        kmer_w = item[letter:letter+18]
        kmers_overlap.append(kmer_w)
        
# Kmer ... without overlap__________________________________
kmers_wo_overlap = []

# Iterate over the sequence
counter =0
for item in seq:
    print(len(item))
    # Iterate over the nucleotides, last nucleotide is shorter than the rest
    for letter in range(0,len(item),18):
        kmer_wo = item[letter:letter+18]'

        kmers_wo_overlap.append(kmer_wo)
